[package]
name = "scuttle"
version = "0.1.0"
edition = "2024"


[dependencies]
clap = { version = "4.5.11", features = ["derive"] }
anyhow = "1.0.86"
tokio = { version = "1.38.1", features = ["full"] }
